theme: jekyll-theme-minimal

# Title
title: Welcome to my personal webpage

#Text
I am an astronomer and Research Scientist at the Center for Mathematical Modelling (CMM) at Universidad de Chile. I am also an associate researcher of the Millennium Institute of Astrophysics (MAS). I am mostly interested in astroinformatics and supernova science. I am the principal invetigator of the High Cadence Transiente Survey (HiTS) and the main coordinator of the ALeRCE project. I led the installation of the CHASE 500 cm robotic telescope in CTIO (first light Oct 2010). I did my Ph.D. thesis on Type Ia Supernovae progenitors at the University of Oxford (2009) with Philipp Podsiadlowski.

My current work focuses in developing an astronomical alert broker, ALeRCE, for large etendue telescopes such as ZTF or LSST.

# This will require each of these plugins automatically.
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin
